return {
    name = "Midnight",
    colors = {
        background = "#000000",
        foreground = "#C0C0C0",
        cursor_bg = "#FFFFFF",
        cursor_fg = "#000000",
        cursor_border = "#FFFFFF",
        selection_fg = "#C0C0C0",
        selection_bg = "#1A1A1A",
        compose_cursor = "#FFFFFF",
        scrollbar_thumb = "#1A1A1A",
        split = "#111111",
        ansi = {
            "#000000",
            "#4A4A4A",
            "#4A4A4A",
            "#6A6A6A",
            "#4A4A4A",
            "#6A6A6A",
            "#6A6A6A",
            "#808080",
        },
        brights = {
            "#333333",
            "#808080",
            "#808080",
            "#A0A0A0",
            "#808080",
            "#A0A0A0",
            "#A0A0A0",
            "#C0C0C0",
        },
        indexed = {},
        tab_bar = {
            background = "#000000",
            active_tab = {
                bg_color = "#111111",
                fg_color = "#FFFFFF",
                intensity = "Normal",
                underline = "None",
                italic = false,
                strikethrough = false,
            },
            inactive_tab = {
                bg_color = "#000000",
                fg_color = "#555555",
                intensity = "Normal",
                underline = "None",
                italic = false,
                strikethrough = false,
            },
            inactive_tab_edge = "#000000",
            inactive_tab_hover = {
                bg_color = "#111111",
                fg_color = "#808080",
            },
            new_tab = {
                bg_color = "#000000",
                fg_color = "#555555",
            },
            new_tab_hover = {
                bg_color = "#111111",
                fg_color = "#FFFFFF",
            },
        },
    },
    window = {
        padding = { left = 4, right = 4, top = 2, bottom = 2 },
        background_opacity = 1.0,
        window_background_opacity = 1.0,
        text_background_opacity = 1.0,
    },
    cursor = {
        style = "Block",
        blink_rate = 0,
        thickness = 1.5,
    },
}
