return {
    name = "Neon",
    colors = {
        background = "#0A0A1A",
        foreground = "#E0E0FF",
        cursor_bg = "#FF00FF",
        cursor_fg = "#000000",
        cursor_border = "#FF00FF",
        selection_fg = "#E0E0FF",
        selection_bg = "#1A1A3A",
        compose_cursor = "#00FFFF",
        scrollbar_thumb = "#1A1A3A",
        split = "#1A1A3A",
        ansi = {
            "#0A0A1A",
            "#FF0044",
            "#00FF88",
            "#FFAA00",
            "#0088FF",
            "#FF00FF",
            "#00FFFF",
            "#8888AA",
        },
        brights = {
            "#444466",
            "#FF3366",
            "#33FFAA",
            "#FFCC33",
            "#33AAFF",
            "#FF44FF",
            "#44FFFF",
            "#AAAAEE",
        },
        indexed = {},
        tab_bar = {
            background = "#0A0A1A",
            active_tab = {
                bg_color = "#1A1A3A",
                fg_color = "#FF00FF",
                intensity = "Normal",
                underline = "None",
                italic = false,
                strikethrough = false,
            },
            inactive_tab = {
                bg_color = "#0A0A1A",
                fg_color = "#444466",
                intensity = "Normal",
                underline = "None",
                italic = false,
                strikethrough = false,
            },
            inactive_tab_edge = "#0A0A1A",
            inactive_tab_hover = {
                bg_color = "#1A1A3A",
                fg_color = "#8888AA",
            },
            new_tab = {
                bg_color = "#0A0A1A",
                fg_color = "#444466",
            },
            new_tab_hover = {
                bg_color = "#1A1A3A",
                fg_color = "#FF00FF",
            },
        },
    },
    window = {
        padding = { left = 10, right = 10, top = 6, bottom = 6 },
        background_opacity = 0.92,
        window_background_opacity = 0.88,
        text_background_opacity = 0.85,
    },
    cursor = {
        style = "Block",
        blink_rate = 800,
        thickness = 2.0,
    },
}
