return {
    name = "Terminux Dark",
    colors = {
        background = "#0B1120",
        foreground = "#E2E8F0",
        cursor_bg = "#84CC16",
        cursor_fg = "#020617",
        cursor_border = "#84CC16",
        selection_fg = "#E2E8F0",
        selection_bg = "#334155",
        compose_cursor = "#84CC16",
        scrollbar_thumb = "#334155",
        split = "#1E293B",
        ansi = {
            "#1E293B",
            "#EF4444",
            "#22C55E",
            "#EAB308",
            "#3B82F6",
            "#A855F7",
            "#06B6D4",
            "#94A3B8",
        },
        brights = {
            "#475569",
            "#F87171",
            "#4ADE80",
            "#FACC15",
            "#60A5FA",
            "#C084FC",
            "#22D3EE",
            "#F8FAFC",
        },
        indexed = {},
        tab_bar = {
            background = "#0B1120",
            active_tab = {
                bg_color = "#1E293B",
                fg_color = "#84CC16",
                intensity = "Normal",
                underline = "None",
                italic = false,
                strikethrough = false,
            },
            inactive_tab = {
                bg_color = "#0F172A",
                fg_color = "#64748B",
                intensity = "Normal",
                underline = "None",
                italic = false,
                strikethrough = false,
            },
            inactive_tab_edge = "#0F172A",
            inactive_tab_hover = {
                bg_color = "#1E293B",
                fg_color = "#94A3B8",
            },
            new_tab = {
                bg_color = "#0F172A",
                fg_color = "#64748B",
            },
            new_tab_hover = {
                bg_color = "#1E293B",
                fg_color = "#84CC16",
            },
        },
    },
    window = {
        padding = { left = 8, right = 8, top = 4, bottom = 4 },
        background_opacity = 0.95,
        window_background_opacity = 0.92,
        text_background_opacity = 0.88,
    },
    cursor = {
        style = "Block",
        blink_rate = 0,
        thickness = 2.0,
    },
}
