return {
    name = "Terminux Light",
    colors = {
        background = "#FFFFFF",
        foreground = "#1E293B",
        cursor_bg = "#6366F1",
        cursor_fg = "#FFFFFF",
        cursor_border = "#6366F1",
        selection_fg = "#1E293B",
        selection_bg = "#CBD5E1",
        compose_cursor = "#6366F1",
        scrollbar_thumb = "#CBD5E1",
        split = "#E2E8F0",
        ansi = {
            "#F1F5F9",
            "#DC2626",
            "#16A34A",
            "#CA8A04",
            "#2563EB",
            "#9333EA",
            "#0891B2",
            "#475569",
        },
        brights = {
            "#CBD5E1",
            "#EF4444",
            "#22C55E",
            "#EAB308",
            "#3B82F6",
            "#A855F7",
            "#06B6D4",
            "#1E293B",
        },
        indexed = {},
        tab_bar = {
            background = "#FFFFFF",
            active_tab = {
                bg_color = "#E2E8F0",
                fg_color = "#6366F1",
                intensity = "Normal",
                underline = "None",
                italic = false,
                strikethrough = false,
            },
            inactive_tab = {
                bg_color = "#F8FAFC",
                fg_color = "#94A3B8",
                intensity = "Normal",
                underline = "None",
                italic = false,
                strikethrough = false,
            },
            inactive_tab_edge = "#F8FAFC",
            inactive_tab_hover = {
                bg_color = "#E2E8F0",
                fg_color = "#64748B",
            },
            new_tab = {
                bg_color = "#F8FAFC",
                fg_color = "#94A3B8",
            },
            new_tab_hover = {
                bg_color = "#E2E8F0",
                fg_color = "#6366F1",
            },
        },
    },
    window = {
        padding = { left = 8, right = 8, top = 4, bottom = 4 },
        background_opacity = 1.0,
        window_background_opacity = 1.0,
        text_background_opacity = 1.0,
    },
    cursor = {
        style = "Block",
        blink_rate = 0,
        thickness = 2.0,
    },
}
